[project]
name = "coldsweat"
version = "0.10.0"
authors = [
  { name="Andrea Peltrin" },
]
description = "Web RSS aggregator and reader compatible with the Fever API"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "peewee >= 3.15.4,<4",
  "requests >= 2.28.1,<3",
  "feedparser >= 6.0.10",
  "flask >= 2.3.0,<3",
  "flask-login >= 0.6.2"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Environment :: Web Environment",
    "Framework :: Flask",
]

[project.urls]
"Homepage" = "https://github.com/passiomatic/coldsweat"
"Bug Tracker" = "https://github.com/passiomatic/coldsweat/issues"

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["coldsweat"]

[tool.setuptools.package-data]
coldsweat = ["static/*.*", "templates/*.html"]